# -*- coding: utf-8 -*-
"""G16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7S2mdJ1Lb3sZVWPgDYYt4eaBIkGsiYU
"""

import re
import math
import random
import time
from collections import Counter

import numpy as np
import pandas as pd
from tqdm import tqdm

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence

from datasets import load_dataset
import sacrebleu

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = True

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

dataset = load_dataset("wmt14", "de-en")

import pandas as pd

train_df = pd.DataFrame(dataset["train"]["translation"])
valid_df = pd.DataFrame(dataset["validation"]["translation"])
test_df = pd.DataFrame(dataset["test"]["translation"])

print(train_df.head())
print(train_df.columns)
print(train_df.shape, valid_df.shape, test_df.shape)

train_df = train_df[["en", "de"]].dropna().reset_index(drop=True)
valid_df = valid_df[["en", "de"]].dropna().reset_index(drop=True)
test_df  = test_df[["en", "de"]].dropna().reset_index(drop=True)

train_df.columns = ["src", "trg"]   # src = English, trg = German
valid_df.columns = ["src", "trg"]
test_df.columns  = ["src", "trg"]

print(train_df.head())

"""## TO RUN BELOW"""

MAX_TRAIN = 80000
MAX_VALID = 5000
MAX_TEST  = 5000

if len(train_df) > MAX_TRAIN:
    train_df = train_df.sample(MAX_TRAIN, random_state=SEED).reset_index(drop=True)

if len(valid_df) > MAX_VALID:
    valid_df = valid_df.sample(MAX_VALID, random_state=SEED).reset_index(drop=True)

if len(test_df) > MAX_TEST:
    test_df = test_df.sample(MAX_TEST, random_state=SEED).reset_index(drop=True)

print(train_df.shape, valid_df.shape, test_df.shape)

def clean_text(text):
    text = str(text).strip()
    text = re.sub(r"\s+", " ", text)
    return text

train_df["src"] = train_df["src"].apply(clean_text)
train_df["trg"] = train_df["trg"].apply(clean_text)

valid_df["src"] = valid_df["src"].apply(clean_text)
valid_df["trg"] = valid_df["trg"].apply(clean_text)

test_df["src"] = test_df["src"].apply(clean_text)
test_df["trg"] = test_df["trg"].apply(clean_text)

def tokenize(text):
    text = text.lower().strip()
    tokens = re.findall(r"\w+|[^\w\s]", text, re.UNICODE)
    return tokens

train_df["src_tokens"] = train_df["src"].apply(tokenize)
train_df["trg_tokens"] = train_df["trg"].apply(tokenize)

valid_df["src_tokens"] = valid_df["src"].apply(tokenize)
valid_df["trg_tokens"] = valid_df["trg"].apply(tokenize)

test_df["src_tokens"] = test_df["src"].apply(tokenize)
test_df["trg_tokens"] = test_df["trg"].apply(tokenize)

train_df[["src_tokens", "trg_tokens"]].head()

MAX_LEN = 50

def keep_length(row):
    return len(row["src_tokens"]) <= MAX_LEN and len(row["trg_tokens"]) <= MAX_LEN

train_df = train_df[train_df.apply(keep_length, axis=1)].reset_index(drop=True)
valid_df = valid_df[valid_df.apply(keep_length, axis=1)].reset_index(drop=True)
test_df  = test_df[test_df.apply(keep_length, axis=1)].reset_index(drop=True)

print(train_df.shape, valid_df.shape, test_df.shape)

SPECIAL_TOKENS = ["<pad>", "<unk>", "<sos>", "<eos>"]

def build_vocab(token_lists, min_freq=2):
    counter = Counter()
    for tokens in token_lists:
        counter.update(tokens)

    vocab = {tok: idx for idx, tok in enumerate(SPECIAL_TOKENS)}

    for token, freq in counter.items():
        if freq >= min_freq and token not in vocab:
            vocab[token] = len(vocab)

    return vocab

src_vocab = build_vocab(train_df["src_tokens"], min_freq=2)
trg_vocab = build_vocab(train_df["trg_tokens"], min_freq=2)

print("Source vocab size:", len(src_vocab))
print("Target vocab size:", len(trg_vocab))

src_itos = {idx: tok for tok, idx in src_vocab.items()}
trg_itos = {idx: tok for tok, idx in trg_vocab.items()}

SRC_PAD_IDX = src_vocab["<pad>"]
SRC_UNK_IDX = src_vocab["<unk>"]
SRC_SOS_IDX = src_vocab["<sos>"]
SRC_EOS_IDX = src_vocab["<eos>"]

TRG_PAD_IDX = trg_vocab["<pad>"]
TRG_UNK_IDX = trg_vocab["<unk>"]
TRG_SOS_IDX = trg_vocab["<sos>"]
TRG_EOS_IDX = trg_vocab["<eos>"]

def numericalize(tokens, vocab, unk_idx, sos_idx, eos_idx):
    ids = [sos_idx]
    ids.extend([vocab.get(tok, unk_idx) for tok in tokens])
    ids.append(eos_idx)
    return ids

train_df["src_ids"] = train_df["src_tokens"].apply(
    lambda x: numericalize(x, src_vocab, SRC_UNK_IDX, SRC_SOS_IDX, SRC_EOS_IDX)
)
train_df["trg_ids"] = train_df["trg_tokens"].apply(
    lambda x: numericalize(x, trg_vocab, TRG_UNK_IDX, TRG_SOS_IDX, TRG_EOS_IDX)
)

valid_df["src_ids"] = valid_df["src_tokens"].apply(
    lambda x: numericalize(x, src_vocab, SRC_UNK_IDX, SRC_SOS_IDX, SRC_EOS_IDX)
)
valid_df["trg_ids"] = valid_df["trg_tokens"].apply(
    lambda x: numericalize(x, trg_vocab, TRG_UNK_IDX, TRG_SOS_IDX, TRG_EOS_IDX)
)

test_df["src_ids"] = test_df["src_tokens"].apply(
    lambda x: numericalize(x, src_vocab, SRC_UNK_IDX, SRC_SOS_IDX, SRC_EOS_IDX)
)
test_df["trg_ids"] = test_df["trg_tokens"].apply(
    lambda x: numericalize(x, trg_vocab, TRG_UNK_IDX, TRG_SOS_IDX, TRG_EOS_IDX)
)

train_df[["src_ids", "trg_ids"]].head()

class TranslationDataset(Dataset):
    def __init__(self, dataframe):
        self.df = dataframe

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        src_ids = torch.tensor(self.df.iloc[idx]["src_ids"], dtype=torch.long)
        trg_ids = torch.tensor(self.df.iloc[idx]["trg_ids"], dtype=torch.long)
        return src_ids, trg_ids

def collate_fn(batch):
    src_batch = [item[0] for item in batch]
    trg_batch = [item[1] for item in batch]

    src_lengths = torch.tensor([len(x) for x in src_batch], dtype=torch.long)

    src_padded = pad_sequence(src_batch, batch_first=True, padding_value=SRC_PAD_IDX)
    trg_padded = pad_sequence(trg_batch, batch_first=True, padding_value=TRG_PAD_IDX)

    return {
        "src": src_padded,
        "src_lengths": src_lengths,
        "trg": trg_padded
    }

BATCH_SIZE = 64
NUM_WORKERS = 2 if torch.cuda.is_available() else 0

train_dataset = TranslationDataset(train_df)
valid_dataset = TranslationDataset(valid_df)
test_dataset  = TranslationDataset(test_df)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_fn,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available()
)

valid_loader = DataLoader(
    valid_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available()
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_fn,
    num_workers=NUM_WORKERS,
    pin_memory=torch.cuda.is_available()
)

class Encoder(nn.Module):
    def __init__(self, input_dim, emb_dim, hid_dim, num_layers=1, dropout=0.2, pad_idx=0):
        super().__init__()
        self.embedding = nn.Embedding(input_dim, emb_dim, padding_idx=pad_idx)
        self.rnn = nn.GRU(
            emb_dim,
            hid_dim,
            num_layers=num_layers,
            dropout=dropout if num_layers > 1 else 0.0,
            batch_first=True
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, src, src_lengths):
        embedded = self.dropout(self.embedding(src))

        packed = nn.utils.rnn.pack_padded_sequence(
            embedded,
            src_lengths.cpu(),
            batch_first=True,
            enforce_sorted=False
        )

        _, hidden = self.rnn(packed)
        return hidden

class Decoder(nn.Module):
    def __init__(self, output_dim, emb_dim, hid_dim, num_layers=1, dropout=0.2, pad_idx=0):
        super().__init__()
        self.output_dim = output_dim
        self.embedding = nn.Embedding(output_dim, emb_dim, padding_idx=pad_idx)
        self.rnn = nn.GRU(
            emb_dim,
            hid_dim,
            num_layers=num_layers,
            dropout=dropout if num_layers > 1 else 0.0,
            batch_first=True
        )
        self.fc_out = nn.Linear(hid_dim, output_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, input_tokens, hidden):
        input_tokens = input_tokens.unsqueeze(1)   # [B] -> [B,1]
        embedded = self.dropout(self.embedding(input_tokens))
        output, hidden = self.rnn(embedded, hidden)
        prediction = self.fc_out(output.squeeze(1))
        return prediction, hidden

class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder, device, sos_idx, eos_idx):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.device = device
        self.sos_idx = sos_idx
        self.eos_idx = eos_idx

        assert encoder.rnn.hidden_size == decoder.rnn.hidden_size
        assert encoder.rnn.num_layers == decoder.rnn.num_layers

    def forward(self, src, src_lengths, trg, teacher_forcing_ratio=0.5):
        batch_size, trg_len = trg.shape
        output_dim = self.decoder.output_dim

        outputs = torch.zeros(batch_size, trg_len, output_dim, device=self.device)

        hidden = self.encoder(src, src_lengths)
        input_tokens = trg[:, 0]

        for t in range(1, trg_len):
            output, hidden = self.decoder(input_tokens, hidden)
            outputs[:, t, :] = output

            teacher_force = random.random() < teacher_forcing_ratio
            top1 = output.argmax(dim=1)
            input_tokens = trg[:, t] if teacher_force else top1

        return outputs

    @torch.no_grad()
    def greedy_decode(self, src, src_lengths, max_len=50):
        batch_size = src.size(0)
        hidden = self.encoder(src, src_lengths)

        input_tokens = torch.full(
            (batch_size,),
            self.sos_idx,
            dtype=torch.long,
            device=self.device
        )

        generated = [input_tokens.unsqueeze(1)]
        finished = torch.zeros(batch_size, dtype=torch.bool, device=self.device)

        for _ in range(max_len):
            output, hidden = self.decoder(input_tokens, hidden)
            top1 = output.argmax(dim=1)

            generated.append(top1.unsqueeze(1))
            finished |= (top1 == self.eos_idx)
            input_tokens = top1

            if finished.all():
                break

        return torch.cat(generated, dim=1)

INPUT_DIM = len(src_vocab)
OUTPUT_DIM = len(trg_vocab)

EMB_DIM = 256
HID_DIM = 512
NUM_LAYERS = 1
DROPOUT = 0.2
LEARNING_RATE = 1e-3
N_EPOCHS = 10
CLIP = 1.0

encoder = Encoder(
    input_dim=INPUT_DIM,
    emb_dim=EMB_DIM,
    hid_dim=HID_DIM,
    num_layers=NUM_LAYERS,
    dropout=DROPOUT,
    pad_idx=SRC_PAD_IDX
)

decoder = Decoder(
    output_dim=OUTPUT_DIM,
    emb_dim=EMB_DIM,
    hid_dim=HID_DIM,
    num_layers=NUM_LAYERS,
    dropout=DROPOUT,
    pad_idx=TRG_PAD_IDX
)

model = Seq2Seq(
    encoder,
    decoder,
    device=device,
    sos_idx=TRG_SOS_IDX,
    eos_idx=TRG_EOS_IDX
).to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
criterion = nn.CrossEntropyLoss(ignore_index=TRG_PAD_IDX)

print(model)

USE_AMP = torch.cuda.is_available()
scaler = torch.cuda.amp.GradScaler(enabled=USE_AMP)

def train_epoch(model, dataloader, optimizer, criterion, clip, device, teacher_forcing_ratio=0.5):
    model.train()
    epoch_loss = 0.0

    for batch in tqdm(dataloader, desc="Training", leave=False):
        src = batch["src"].to(device, non_blocking=True)
        src_lengths = batch["src_lengths"].to(device, non_blocking=True)
        trg = batch["trg"].to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)

        with torch.cuda.amp.autocast(enabled=USE_AMP):
            output = model(src, src_lengths, trg, teacher_forcing_ratio=teacher_forcing_ratio)
            output_dim = output.shape[-1]

            output = output[:, 1:, :].reshape(-1, output_dim)
            trg_y = trg[:, 1:].reshape(-1)

            loss = criterion(output, trg_y)

        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), clip)
        scaler.step(optimizer)
        scaler.update()

        epoch_loss += loss.item()

    return epoch_loss / len(dataloader)

@torch.no_grad()
def evaluate_epoch(model, dataloader, criterion, device):
    model.eval()
    epoch_loss = 0.0

    for batch in tqdm(dataloader, desc="Evaluating", leave=False):
        src = batch["src"].to(device, non_blocking=True)
        src_lengths = batch["src_lengths"].to(device, non_blocking=True)
        trg = batch["trg"].to(device, non_blocking=True)

        with torch.cuda.amp.autocast(enabled=USE_AMP):
            output = model(src, src_lengths, trg, teacher_forcing_ratio=0.0)
            output_dim = output.shape[-1]

            output = output[:, 1:, :].reshape(-1, output_dim)
            trg_y = trg[:, 1:].reshape(-1)

            loss = criterion(output, trg_y)

        epoch_loss += loss.item()

    return epoch_loss / len(dataloader)

def epoch_time(start_time, end_time):
    elapsed = end_time - start_time
    mins = int(elapsed // 60)
    secs = int(elapsed % 60)
    return mins, secs

best_valid_loss = float("inf")

for epoch in range(N_EPOCHS):
    start_time = time.time()

    train_loss = train_epoch(
        model,
        train_loader,
        optimizer,
        criterion,
        clip=CLIP,
        device=device,
        teacher_forcing_ratio=0.5
    )

    valid_loss = evaluate_epoch(
        model,
        valid_loader,
        criterion,
        device=device
    )

    end_time = time.time()
    epoch_mins, epoch_secs = epoch_time(start_time, end_time)

    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(model.state_dict(), "best_seq2seq_baseline.pt")

    print(f"Epoch: {epoch+1:02d} | Time: {epoch_mins}m {epoch_secs}s")
    print(f"  Train Loss: {train_loss:.4f}")
    print(f"  Valid Loss: {valid_loss:.4f}")

def ids_to_tokens(ids, itos, eos_idx, pad_idx, sos_idx):
    tokens = []
    for idx in ids:
        if idx == eos_idx:
            break
        if idx in (pad_idx, sos_idx):
            continue
        tokens.append(itos.get(idx, "<unk>"))
    return tokens

@torch.no_grad()
def compute_bleu(model, dataloader, trg_itos, device, max_len=50):
    model.eval()

    predictions = []
    references = []

    for batch in tqdm(dataloader, desc="BLEU", leave=False):
        src = batch["src"].to(device, non_blocking=True)
        src_lengths = batch["src_lengths"].to(device, non_blocking=True)
        trg = batch["trg"].to(device, non_blocking=True)

        pred_ids = model.greedy_decode(src, src_lengths, max_len=max_len)

        for i in range(src.size(0)):
            pred_tokens = ids_to_tokens(
                pred_ids[i].tolist(),
                trg_itos,
                eos_idx=TRG_EOS_IDX,
                pad_idx=TRG_PAD_IDX,
                sos_idx=TRG_SOS_IDX
            )

            gold_tokens = ids_to_tokens(
                trg[i].tolist(),
                trg_itos,
                eos_idx=TRG_EOS_IDX,
                pad_idx=TRG_PAD_IDX,
                sos_idx=TRG_SOS_IDX
            )

            predictions.append(" ".join(pred_tokens))
            references.append(" ".join(gold_tokens))

    bleu = sacrebleu.corpus_bleu(predictions, [references])
    return bleu.score, predictions, references

bleu_score, test_predictions, test_references = compute_bleu(
    model,
    test_loader,
    trg_itos,
    device=device,
    max_len=MAX_LEN
)

print(f"Test BLEU: {bleu_score:.2f}")